#!/usr/bin/env ruby

require 'fileutils'
require './DatasetLooper.rb'
looper = DatasetLooper.new

outN = "tables/img.tex"
out = File.open(outN,"w")
out.puts "%%%%% latex generated by #{$0} %%%%%"
NumRows = 3
DatasetLooper::BinHash.each do |ivType,binOpts|
  row = 0

  torii = ['inbending','outbending','bibending']

  # list of lists: [ [inbending pngs], [outbending pngs], [bibending pngs] ]
  toriiPngs = torii.map do |torus|
    Dir.glob("tables/img.#{torus}.#{ivType}/*.png").sort
  end
  NumPngs = toriiPngs.first.length

  toriiPngs.inject(:zip).map(&:flatten).each do |pngs|

    if row%NumRows==0
      out.puts "\\begin{figure}[h]"
      out.puts "\\centering"
    end

    pngs.each do |png|
      out.puts "\\includegraphics[width=0.32\\textwidth]{img/#{png}}"
    end

    if row%NumRows==NumRows-1 or row==NumPngs-1
      caption = "Kinematic means, in bins of #{binOpts[:xTitle]}."
      if row==NumRows-1
        caption += " Continued on next figure."
      else
        caption += " Continued from previous figure."
      end
      out.puts "\\caption{#{caption}}"
      out.puts "\\label{fig:meanvmean:#{ivType}:#{row/NumRows}}"
      out.puts "\\end{figure}"
    end

    row += 1
  end
end

out.puts "%%%%% end generated markup %%%%%"
out.close
puts "wrote #{outN}"
