#!/usr/bin/env ruby

require 'fileutils'
require './DatasetLooper.rb'
looper = DatasetLooper.new

outN = "meanvmean/img.tex"
out = File.open(outN,"w")
out.puts "%%%%% latex generated by #{$0} %%%%%"
NumRows = 3 # try to keep this number equal to the number of higher dimensional bins, e.g., z-dependence in `NumRows` bins of M_h
DatasetLooper::BinHash.each do |ivType,binOpts|

  row = 0
  highDim = false
  highDimVar = ''
  tori = ['inbending','outbending','bibending']

  # list of lists: [ [inbending pngs], [outbending pngs], [bibending pngs] ]
  toriPngs = tori.map do |torus|
    Dir.glob("meanvmean/img.#{torus}.#{ivType}/*.png").sort
  end
  numPngs = toriPngs.first.length

  # zip together the png lists from the three tori, and iterate over each triple of pngs
  toriPngs.inject(:zip).map(&:flatten).each do |pngs|

    # header
    if row%NumRows==0
      out.puts "\\begin{figure}[p]"
      out.puts "\\centering"
    end

    # include graphics
    pngs.each do |png|
      out.puts "\\includegraphics[width=0.32\\textwidth]{img/#{png}}"
      highDim=true if png.split('_').last.include?('Bin')  # detect if this is a 2D or 3D binning scheme
      highDimVar="$M_h$" if highDim # FIXME: should automatically figure out what the higher dimensional bin actually is, for now we only have M_h
    end

    # caption, label, footer
    if row%NumRows==NumRows-1 or row==numPngs-1
      caption = "Kinematic means, in bins of #{binOpts[:xTitle].gsub(/ \[.*$/,'')}."
      caption.sub!(/\.$/,", with rows corresponding to the #{NumRows} #{highDimVar} bins.") if highDim
      caption += " Inbending data are in the left column, outbending in the middle, and the combined inbending and outbending data are in the right column."
      caption += " Light red closed (open) circles with solid (dashed) lines are for RGA data (MC)."
      caption += " Dark blue closed (open) squares with solid (dashed) lines are for RGB data (MC)."
      if row==NumRows-1
        caption += " Continued on next figure."
      else
        caption += " Continued from previous figure."
      end
      out.puts "\\caption{#{caption}}"
      out.puts "\\label{fig:meanvmean:#{ivType}:#{row/NumRows}}"
      out.puts "\\end{figure}"
    end

    row += 1
  end
end

out.puts "%%%%% end generated latex %%%%%"
out.close
puts "wrote #{outN}"
