// THIS FILE WAS GENERATED BY ./generate_beam_energy_config.rb, which used RCDB to get the beam energies
#ifndef BEAMENERGYTABLE_H_GUARD
#define BEAMENERGYTABLE_H_GUARD

#include <map>

class BeamEnergyTable {
  public:
    static std::map<int,float> const table;
};

#endif
