#ifndef QADBCONFIG_H_GUARD
#define QADBCONFIG_H_GUARD

#include <QADB.h>

// handles the QADB criteria: which defect bits to omit and how to handle `Misc` defect assignments
class QADBConfig {
  public:

    static void Setup(std::unique_ptr<QA::QADB>& qa) {

      // choose which defect bits to filter out
      std::vector<std::string> reject_these_defects = {
        "TotalOutlier",   "TerminalOutlier",   "MarginalOutlier",   "SectorLoss",
        "TotalOutlierFT", "TerminalOutlierFT", "MarginalOutlierFT", "LossFT",
        "BSAUnknown",
        "ChargeHigh", "ChargeNegative", "ChargeUnknown",
        "PossiblyNoBeam",
        "Misc"
      };

      // list of runs where if a QA bin ONLY has the `Misc` defect, then ALLOW that bin
      /* GENERATED BY THE FOLLOWING COMMAND, and revised
         qadb-info misc \
           --code '//' \
           --datasets pass2/rga_fa18_inbending,pass2/rga_fa18_outbending,pass2/rga_sp19,pass2/rgb_fa19,pass2/rgb_sp19,pass2/rgb_wi20
       */
      /* REASONS FOR ALLOWING:
       * - no statistically significant impact on the pi+ BSA (timeline)
       * - unrelated to the FD pions and electron
       * REASONS FOR REJECTING: (other than not satisfying a REASON FOR ALLOWING):
       * - the run is very short, likely because of the Misc bit reason
       * NOTE: these REASONS are documented below as ADDITIONAL COMMENTS, e.g.,
       *   5032 // QADB Comment // My reasoning
       */
      std::vector<int> allow_these_misc_assignments = {

        /* rga.inbending.fa18 */
        // 5032,    // TDC window adjustment
        5046,    // MVT HV off // no impact on pion BSA
        5047,    // MVT HV off // no impact on pion BSA
        5051,    // MVT HV off // no impact on pion BSA
        5116,    // MVT detector 2 and 15 are off // no impact on pion BSA
        5117,    // MVT detector 2 and 15 are off // no impact on pion BSA
        // 5119,    // scaler1 was in disconnected state
        // 5127,    // DC test: Short run with reduced DC readout window
        5128,    // fraction of events with defined helicity is low // no impact on pion BSA
        5129,    // fraction of events with defined helicity is low // no impact on pion BSA
        5130,    // fraction of events with defined helicity is low // no impact on pion BSA
        // 5137,    // ignorable, according to shift expert
        // 5138,    // short DC windows with offset and CND offset changed
        5158,    // fraction of events with defined helicity is low // no impact on pion BSA
        5159,    // fraction of events with defined helicity is low // no impact on pion BSA
        5160,    // fraction of events with defined helicity is low // no impact on pion BSA
        5163,    // fraction of events with defined helicity is low // no impact on pion BSA
        5165,    // fraction of events with defined helicity is low // no impact on pion BSA
        5166,    // fraction of events with defined helicity is low // no impact on pion BSA
        5167,    // fraction of events with defined helicity is low // no impact on pion BSA
        5168,    // fraction of events with defined helicity is low // no impact on pion BSA
        5169,    // fraction of events with defined helicity is low // no impact on pion BSA
        5180,    // fraction of events with defined helicity is low // no impact on pion BSA
        5181,    // fraction of events with defined helicity is low // no impact on pion BSA
        5182,    // fraction of events with defined helicity is low // no impact on pion BSA
        5183,    // fraction of events with defined helicity is low // no impact on pion BSA
        // 5194,    // beam was mostly off during this run
        // 5215,    // special run: HTCC trig. threshold set to 1 phe
        // 5225,    // high rates, trippy beam, varying current
        // 5229,    // Beam is tripping continuously
        // 5300,    // empty target run
        // 5301,    // empty target run
        // 5302,    // empty target run
        // 5316,    // production, ctof and svt issues // there are also FTOF issues
        // 5325,    // torus at 60%, changed beam current to 30 nA at 1 pm
        // 5335,    // issue with dc13 at the end // very short run
        // 5336,    // dc13 issue at the end again // very short run
        5362,    // solenoid trip at the end // timelines look okay
        5369,    // DAQ lifetime issue at the end (not clear why) // timelines look okay
        // 5370,    // Issue with tdc in ftof ecal sector 5
        // 5371,    // Missing Half of FTCal // very short run
        // 5377,    // rich4 ROC became un-responsive // very short run
        // 5390,    // adcftof3vtp serdes PP14 down // very short run
        // 5398,    // BST chip latch up // short run, pion BSA looks reasonable, but there were other possibly related problems in neighboring runs, so rejecting for analysis
        // 5400,    // an SVT layer latch up // short run, pion BSA looks reasonable, but there were other possibly related problems in neighboring runs, so rejecting for analysis
        // 5402,    // Multiple issues (CTOF, ECAL...) in monitoring
        // 5403,    // helicity problem in monitor; pion BSA looks okay // rejecting for safety
        // 5404,    // helicity problem in monitor; pion BSA looks okay // rejecting for safety
        // 5414,    // no htcc in trigger // many N/F outliers
        // 5415,    // no htcc in trigger, BST chip latch up // many N/F outliers
        // 5416,    // no htcc in trigger // many N/F outliers
        // 5417,    // no htcc in trigger // many N/F outliers
        // 5418,    // low lumi run
        // 5419,    // low lumi run

        /* rga.outbending.fa18 */
        // 5423,    // DC validation trigger // pion BSA looks okay, but uses different trigger file
        5434,    // lost connection to ECAL sector 2; data may still be okay though // QA timelines look okay
        // 5435,    // FC charge issue // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 5439,    // CTOF scalers looked bad // very short run
        // 5443,    // low lumi run, 5 nA
        // 5444,    // low lumi run, 20 nA
        5448,    // N/F for DVCS exclusivity cuts is 25% lower than adjacent runs; however, trigger N/F is consistent // pion BSA looks normal
        // 5450,    // trigger bit issue // short run
        // 5456,    // low lumi run, 15 nA (for most of it); TDC problem in FTOF sector 5
        // 5457,    // low lumi run, 16 nA; problem in HTCC sector 2
        // 5462,    // dc42 links down // very short run, not much beam
        // 5495,    // BST occupancy plots empty // pion BSA looks smaller than normal
        // 5496,    // empty BST occupancy // very short run
        // 5504,    // unstable beam; DAQ problem at end of run // only 5 minutes with beam
        5505,    // this marks the run where the current changed from 40 to 50 nA; it changed about halfway through this run // pion BSA unaffected by this change
        5521,    // SVT latchup problem; not clear if this was for the whole run, or just near the end // pion BSA and other timelines look okay
        // 5542,    // TRGbit=2 not present // very short run
        // 5546,    // trigger bit 6 lost // very short run
        // 5554,    // N/F in sector 1 is slightly lower than normal, for the whole run, but not enough to be an outlier // rejected for safety
        // 5564,    // low lumi run, 5 nA; fraction of events with defined helicity is low
        // 5565,    // low lumi run, 5 nA; fraction of events with defined helicity is low
        // 5566,    // low lumi run, 5 nA; fraction of events with defined helicity is low
        5567,    // fraction of events with defined helicity is low // no impact on pion BSA
        // 5586,    // empty target
        // 5589,    // empty target
        // 5590,    // empty target
        // 5594,    // new trigger file // very short run
        // 5595,    // 70 nA run; no FT trigger // test run, actually, higher current than normal production
        5597,    // no FT trigger // pion BSA looks okay, and N/F looks normal
        // 5600,    // RICH alarm for tile 0,18 // very short run
        // 5602,    // 5 nA for the first 5 minutes of data taking // reject, since it's just the first several QA bins
        // 5607,    // FC charge issue // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 5610,    // SVT readout chip has zero scalers and corresponding occupancy plot has missing strip // very short run
        // 5615,    // 5 nA and increasing current at beginning of this run // just affects the first 25 bins
        // 5617,    // junk
        // 5620,    // ramping beam current 5 to 50 nA // short run
        5621,    // CND TDC problem // this analysis does not use the CND
        5623,    // CND TDC problem, ROC rebooted while DAQ was running // this analysis does not use the CND
        // 5652,    // Problem with scalers in EPICS GUI. Stopped the run to try solve the issue. Not sure if it is junk. // reject for safety

        /* rga.inbending.sp19 */
        // 6616,    // low lumi run
        // 6618,    // low lumi run
        6631,    // fraction of events with defined helicity is low; pi+ beam asymmetry looks normal // no impact on pion BSA
        6632,    // fraction of events with defined helicity is low; pi+ beam asymmetry looks normal // no impact on pion BSA
        // 6696,    // FC charge issue // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 6697,    // FC charge issue // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 6699,    // FC charge issue // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 6710,    // FC charge issue // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 6722,    // rgb_v9_1_faraday_noprescale trigger configuration; beam current is 10 nA
        // 6723,    // low lumi run
        // 6724,    // empty target run
        // 6725,    // empty target run
        // 6730,    // N/F for sector 5 is slightly lower than that for adjacent runs, but not outlying // reject for safety
        6734,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6736,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6737,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6738,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6739,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6740,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6741,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6742,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6743,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6744,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6746,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6747,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6748,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6749,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6750,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6753,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6754,    // FC charge issue; FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA; bins which have FC charge issue are outliers and therefore are already filtered out
        6755,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6756,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        6757,    // FADC failure in ECAL sector 6; see https://logbooks.jlab.org/entry/3678262 // no impact on pion BSA
        // 6760,    // FC charge issue // reject, since N/F is not correct; it's just the first few QA bins anyway
        6775,    // fraction of events with defined helicity is low; pi+ beam asymmetry looks normal // no impact on pion BSA
        6776,    // fraction of events with defined helicity is low; pi+ beam asymmetry looks normal // no impact on pion BSA
        6777,    // fraction of events with defined helicity is low; pi+ beam asymmetry looks normal // no impact on pion BSA
        6778,    // fraction of events with defined helicity is low; pi+ beam asymmetry looks normal // no impact on pion BSA

        /* rgb.inbending.sp19 */
        6156,    // FTH and FTT HV off // no impact on pion BSA
        // 6167,    // low lumi run, 10 nA
        // 6168,    // low lumi run, 10 nA
        // 6169,    // low lumi run, 10 nA
        // 6170,    // low lumi run, 10 nA
        6190,    // Run ended due to bug in trig file // no impact on pion BSA
        // 6199,    // production run - short - lot of beam trips // very short run
        // 6208,    // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        6219,    // FT alarm: B_DET_FTT_FEU:NActivecrates https://logbooks.jlab.org/entry/3652961. 3 NActive cates: https://logbooks.jlab.org/entry/3652984 // no impact on pion BSA
        6220,    // FT alarm: B_DET_FTT_FEU:NActivecrates https://logbooks.jlab.org/entry/3652961. 3 NActive cates: https://logbooks.jlab.org/entry/3652984 // no impact on pion BSA
        // 6222,    // production. Lots of beam trips and MVT channel trips. // reject for safety, pion BSA statistics are rather low
        // 6226,    // low lumi run, 5 nA
        // 6227,    // low lumi run, 15 nA
        // 6254,    // radiation monitor tripped in the Hall truck ramp // very short run
        // 6262,    // empty target run
        // 6263,    // empty target run
        // 6265,    // band harp wire run
        // 6266,    // possibly a test run after vtp libraries changed // very short run
        // 6287,    // mmft1 ROC issue; no helicity info
        6298,    // Production with new trigger configuration, current started at 35 nA, then increased to 50 nA // pion BSA looks fine
        // 6310,    // slight decrease in N/F for sector 2 // reject for safety
        // 6322,    // low lumi run, 5 nA
        // 6323,    // low lumi run, 5 nA
        // 6342,    // alignment run
        // 6346,    // FC charge issue at beginning of run; slight decrease in N/F for sector 3 // reject for safety
        // 6350,    // empty target run
        // 6356,    // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 6357,    // FC charge issue at beginning of run; unstable yield, possibly due to 5 nA beam current // reject, since N/F is not correct; Misc defect bits are assigned only for the first few QA bins
        6363,    // beam current at 40 nA instead of the usual 50 nA
        // 6371,    // low lumi run, 5 nA
        // 6373,    // low lumi run, 5 nA
        // 6374,    // low lumi run, 5 nA
        6378,    // only run with correct HWP sign, therefore pion BSA and helicity sign are correct // the helicity sign is automatically corrected in this analysis, using the QADB
        // 6385,    // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 6386,    // no helicity info for QA bins 15 to 60; both N and F are very low, but N/F looks normal; unknown cause // reject since no helicity info
        // 6389,    // empty target run
        6396,    // no MVT1 // pion BSA looks normal
        6420,    // Lower yields sector 6; DC sector 6 channel issues? // the sector-6 yield is only slightly lower
        // 6431,    // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        6437,    // sector 2 yields slightly low, possibly due to dead ECout v strips; see https://logbooks.jlab.org/entry/3665957 // the sector-2 yield is only slightly lower
        6442,    // sector 2 yields slightly low, possibly due to dead ECout v strips; see https://logbooks.jlab.org/entry/3665957 // the sector-2 yield is only slightly lower
        6443,    // sector 2 yields slightly low, possibly due to dead ECout v strips; see https://logbooks.jlab.org/entry/3665957 // the sector-2 yield is only slightly lower
        6444,    // sector 2 yields slightly low, possibly due to dead ECout v strips; see https://logbooks.jlab.org/entry/3665957 // the sector-2 yield is only slightly lower
        6445,    // sector 2 yields slightly low, possibly due to dead ECout v strips; see https://logbooks.jlab.org/entry/3665957 // the sector-2 yield is only slightly lower
        // 6446,    // low lumi run, 5 nA; sector 4 went down for the last several QA bins
        // 6447,    // low lumi run, 5 nA
        // 6448,    // low lumi run, 5 nA
        // 6455,    // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 6460,    // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 6466,    // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 6470,    // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 6472,    // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 6476,    // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        6548,    // many QA bins have low fraction of events with helicity info, starting from QA bin 31 // pion BSA looks normal
        // 6551,    // mmft1 ROC busy; no helicity info; probably junk
        // 6557,    // N/F slightly lower for sector 6, from QA bin 75 onward // reject for safety, and the Misc defect bit only applies to part of the run
        // 6561,    // unstable beam current in Hall B; beam tune to Hall C; missing DC channels; junk // very short run anyway
        // 6562,    // beam current started at 40 nA, but was increased to 50 nA for the last 1/4 of the run // reject since pion BSA looks too small (but also its statistics are poor)
        // 6591,    // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 6596,    // PCAL and ECAL TDC ROCS for sector 5 give error messages // reject, sector 5 is a total outlier for the entire run
        // 6599,    // empty target run
        // 6601,    // empty target run
        // 6603,    // empty target run

        /* rgb.outbending.fa19 */
        // 11117,   // low lumi run, 7 nA
        // 11119,   // empty target run
        // 11120,   // low lumi run, 7 nA
        // 11121,   // mild reduction in N/F for sector 2 // reject for safety, it is only the last part of the run
        11126,   // Lower beam current; Running briefly at 20nA instead of 40nA // pion BSA looks normal
        11132,   // Higher normalized yields this run due to slightly smaller FC charge readouts // pion BSA looks normal
        // 11143,   // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 11162,   // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 11195,   // trigger bit alarm // reject, since only affects the last few QA bins
        // 11200,   // low lumi run, 7 nA
        // 11201,   // low lumi run, 7 nA
        // 11202,   // low lumi run, 7 nA
        // 11203,   // low lumi run, 7 nA
        // 11206,   // low lumi run, 7 nA
        // 11207,   // low lumi run, 7 nA
        // 11210,   // low lumi run, 20 nA
        // 11221,   // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 11244,   // test run
        // 11269,   // Small reduction in N/F for sector 2 // reject for safety, it is only the last part of the run
        // 11287,   // update trigger file to add FT triggers // already excluded, since this is a run in the 4 GeV inbending period

        /* rgb.inbending.wi20 */
        // 11323,   // low lumi run, 5 nA; during setup period
        // 11324,   // low lumi run, 10 nA; during setup period
        // 11325,   // low lumi run, 10 nA; during setup period
        // 11326,   // Short run at 30 nA to make sure DAQ is good; during setup period
        // 11327,   // 50 nA production run - lots of problems with DC HV trips; during setup period
        // 11328,   // during setup period
        // 11329,   // low lumi run, 20 nA; during setup period
        // 11330,   // low lumi run, 20 nA; during setup period
        // 11331,   // Taken during spin dance (20nA); during setup period
        // 11336,   // low livetime (0.8) for most of the run; fraction of events with defined helicity is low; during setup period
        // 11338,   // low livetime (0.7-0.8) for most of the run; fraction of events with defined helicity is low; during setup period
        // 11339,   // during setup period
        // 11340,   // beam modulation problems; during setup period
        // 11341,   // beam modulation problems; during setup period
        // 11342,   // beam modulation problems; bad trigger timing; fraction of events with defined helicity is low; during setup period
        // 11345,   // low livetime (0.7) for most of the run; fraction of events with defined helicity is low; during setup period
        // 11347,   // varied beam current; RF phase tuning; during setup period
        // 11348,   // continued RF phase tuning; during setup period
        // 11352,   // RF phase tuning; during setup period
        // 11354,   // RF phase tuning; fraction of events with defined helicity is low; during setup period
        // 11356,   // RF phase tuning; varied beam current; during setup period; fraction of events with defined helicity is low; during setup period
        // 11357,   // low livetime (0.75) for most of the run; fraction of events with defined helicity is low; during setup period
        // 11358,   // low livetime (0.8) for most of the run; fraction of events with defined helicity is low; during setup period
        // 11361,   // FC charge issue at beginning of run; during setup period
        // 11362,   // slight decrease in N/F for sector 3 // reject for safety, it is only the last part of the run
        // 11364,   // slight decrease in N/F for sector 4 // reject for safety, it is only the last part of the run
        // 11372,   // used different trigger file, rgb_v9_1.cnf; N/F lower than usual; Beam current changed to 50 nA // reject for safety
        // 11394,   // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 11395,   // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 11414,   // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 11421,   // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 11444,   // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 11485,   // low lumi run, 10 nA
        // 11486,   // low lumi run, 10 nA
        // 11487,   // low lumi run, 10 nA
        // 11502,   // beam current oscillations: https://logbooks.jlab.org/entry/3770100 // reject for safety
        // 11505,   // FC charge issue at beginning of run // reject, since N/F is not correct; it's just the first few QA bins anyway
        // 11521,   // Bad beam quality: Multiple DC channel trips due to beam current spikes
        // 11544,   // poor beam current stability // reject for safety
        // 11548,   // the beam is pretty awful and this run is junk, says the logbook
        // 11557,   // beam steering issues, causing increased F and a bit of variation in N/F // reject for safety
      };

      //////////////////////////////////////////////////////////////////////////////////

      // apply the settings
      for(auto defect : reject_these_defects)
        qa->CheckForDefect(defect.c_str());
      for(auto run : allow_these_misc_assignments)
        qa->AllowMiscBit(run);

    }
};

#endif
